name: "CI/CD Pipeline with Logging"

on:
  push:
    branches:
      - main

jobs:
  logging_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub Action Logging Pre-op
        uses: DaggupatiPavan/demo124@v1
        with:
          version: "v1.0.0"
          log_level: "INFO"
          #api_url: "https://your-api.com/logs"
